export const tutorialSteps = {
  overviewNav: {
    id: 'overviewNav',
    title: 'Overview (OV)',
    description: 'Overview dashboard walkthrough',
    duration: '3 min',
    difficulty: 'beginner',
    route: '/home',
    steps: [
      {
        target: '.page-heading',
        content: 'This is your Overview dashboard with recent agents and status highlights.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.workspace-nav',
        content: 'Use the sidebar to jump to Builder, Marketplace, Canvas, and more.',
        placement: 'right',
        type: 'info',
      },
      {
        target: 'body',
        content: 'That’s the Overview hub. Use it to monitor your agents at a glance.',
        placement: 'center',
        type: 'info',
      },
    ],
  },
  introToAgents: {
    id: 'introToAgents',
    title: 'Introduction to AI Agents',
    description: 'Learn the basics of AI agents and how to use them',
    duration: '5 min',
    difficulty: 'beginner',
    route: '/home',
    steps: [
      {
        target: '.brand',
        content: 'Welcome to the AI Agent platform! This is your dashboard where you can manage all your agents.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.dashboard-grid',
        content: "Here you can see all your agents. Each card shows an agent's details, status, and available actions.",
        placement: 'left',
        type: 'info',
      },
      {
        target: 'body',
        content: 'Quick quiz: What is the main purpose of an AI Agent?',
        placement: 'center',
        type: 'quiz',
        options: [
          'To replace human workers entirely',
          'To automate tasks and assist users with specific goals',
          'To store data in the cloud',
          'To create websites'
        ],
        correctAnswer: 1,
        points: 10,
      },
      {
        target: '.chat-icon-btn',
        content: 'Click here to test a single agent in the Chat interface.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.multi-chat-icon-btn',
        content: 'Or click here to have multiple agents discuss topics together!',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: 'body',
        content: 'Which button would you click to have a conversation with a SINGLE agent?',
        placement: 'center',
        type: 'quiz',
        options: [
          'The Multi-Chat button (🤖💬)',
          'The Chat button (💬)',
          'The Profile button',
          'The Voice Chat button (🎤)'
        ],
        correctAnswer: 1,
        points: 10,
      },
      {
        target: '.profile-btn',
        content: 'You can access your profile settings from here.',
        placement: 'left',
        type: 'info',
      },
      {
        target: 'body',
        content: "Great! You've completed the introduction. Ready to create your first agent?",
        placement: 'center',
        type: 'info',
      },
    ],
  },

  buildingYourFirstAgent: {
    id: 'buildingYourFirstAgent',
    title: 'Building Your First Agent',
    description: 'Step-by-step guide to create your first AI agent',
    duration: '10 min',
    difficulty: 'beginner',
    route: '/builder',
    steps: [
      {
        target: 'body',
        content: 'Welcome to the Agent Builder! This is where you create and configure your AI agents.',
        placement: 'center',
        type: 'info',
      },
      {
        target: 'body',
        content: 'Before we start, what do you think a "System Prompt" does for an AI agent?',
        placement: 'center',
        type: 'quiz',
        options: [
          'It displays error messages',
          'It defines the agent\'s personality and behavior',
          'It stores user passwords',
          'It creates the user interface'
        ],
        correctAnswer: 1,
        points: 10,
      },
      {
        target: 'input[placeholder*="Agent name"]',
        content: 'Give your agent a meaningful name. Try naming it something descriptive!',
        placement: 'bottom',
        type: 'task',
        taskId: 'name-agent',
        taskDescription: 'Type a name for your agent in the input field above',
        points: 15,
      },
      {
        target: 'textarea[placeholder*="description"]',
        content: 'Describe what your agent will do. Be specific about its purpose.',
        placement: 'bottom',
        type: 'task',
        taskId: 'describe-agent',
        taskDescription: 'Write a description for your agent',
        points: 15,
      },
      {
        target: 'select',
        content: 'Choose the AI model that will power your agent. Different models have different capabilities.',
        placement: 'right',
        type: 'info',
      },
      {
        target: 'body',
        content: 'Which model would you choose for creative writing tasks?',
        placement: 'center',
        type: 'quiz',
        options: [
          'Any model - they are all the same',
          'A model with higher creativity settings',
          'The cheapest model only',
          'Models cannot do creative writing'
        ],
        correctAnswer: 1,
        points: 10,
      },
      {
        target: 'textarea[placeholder*="system prompt"]',
        content: "Write the system prompt. This defines your agent's behavior, personality, and how it should respond.",
        placement: 'left',
        type: 'task',
        taskId: 'write-system-prompt',
        taskDescription: 'Write a system prompt that defines how your agent should behave',
        points: 20,
      },
      {
        target: 'body',
        content: "Excellent work! You've learned how to build an AI agent. Save it to see it on your dashboard!",
        placement: 'center',
        type: 'info',
      },
    ],
  },

  overviewNavigation: {
    id: 'overviewNavigation',
    title: 'Overview Navigation',
    description: 'Learn where each section lives in the sidebar',
    duration: '6 min',
    difficulty: 'beginner',
    route: '/home',
    steps: [
      {
        target: '.workspace-nav',
        content: 'This sidebar is your command map. Every section is one click away.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(1)',
        content: 'OV · Overview: your agent dashboard and status.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(2)',
        content: 'BL · Builder: design and tune your agents.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(3)',
        content: 'MP · Marketplace: browse and share agents.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(4)',
        content: 'CV · Flow Canvas: visual orchestration and workflows.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(5)',
        content: 'TP · Templates: starter kits and examples.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(6)',
        content: 'TS · Testing Lab: A/B testing and QA.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(7)',
        content: 'CH · Chat: single agent chat surface.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(8)',
        content: 'MA · Multi-Agent: swarm chat.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(9)',
        content: 'AT · Autonomous: task runner.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(10)',
        content: 'FL · Fusion Lab: blend agents.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(11)',
        content: 'EL · Evolution Lab: refine iteratively.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.nav-links .nav-link:nth-child(12)',
        content: 'AN · Analytics: performance insights.',
        placement: 'right',
        type: 'info',
      },
      {
        target: 'body',
        content: 'You now know every section. Pick one to continue!',
        placement: 'center',
        type: 'info',
      },
    ],
  },
  builderNav: {
    id: 'builderNav',
    title: 'Builder (BL)',
    description: 'Design & tune agents',
    duration: '4 min',
    difficulty: 'beginner',
    route: '/builder',
    steps: [
      {
        target: '.page-heading',
        content: 'This is the Builder. Configure name, prompt, tools, and model.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.config-column',
        content: 'Use the left column to edit core agent settings.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.chat-column',
        content: 'Test the agent on the right before publishing.',
        placement: 'left',
        type: 'info',
      },
    ],
  },
  marketplaceNav: {
    id: 'marketplaceNav',
    title: 'Marketplace (MP)',
    description: 'Browse & share agents',
    duration: '3 min',
    difficulty: 'beginner',
    route: '/marketplace',
    steps: [
      {
        target: '.marketplace-page header',
        content: 'Marketplace lists public, published agents.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.marketplace-filters',
        content: 'Search and sort by popularity or rating here.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.marketplace-grid',
        content: 'Each card can be forked or rated.',
        placement: 'top',
        type: 'info',
      },
    ],
  },
  templatesNav: {
    id: 'templatesNav',
    title: 'Templates (TP)',
    description: 'Starter kits and examples',
    duration: '3 min',
    difficulty: 'beginner',
    route: '/templates',
    steps: [
      {
        target: '.page-heading',
        content: 'Templates are ready-to-use starting points.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.template-grid',
        content: 'Choose a template to import or customize.',
        placement: 'top',
        type: 'info',
      },
    ],
  },
  testingLabNav: {
    id: 'testingLabNav',
    title: 'Testing Lab (TS)',
    description: 'A/B testing and QA',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/testing',
    steps: [
      {
        target: '.page-heading',
        content: 'Testing Lab helps you evaluate agent responses.',
        placement: 'bottom',
        type: 'info',
      },
      {
        target: '.testing-shell',
        content: 'Run multiple prompts and compare outcomes.',
        placement: 'top',
        type: 'info',
      },
    ],
  },
  chatNav: {
    id: 'chatNav',
    title: 'Chat (CH)',
    description: 'Single agent chat surface',
    duration: '3 min',
    difficulty: 'beginner',
    route: '/chat',
    steps: [
      {
        target: '.chat-rail',
        content: 'Pick a published agent from the list.',
        placement: 'right',
        type: 'info',
      },
      {
        target: '.stage-window',
        content: 'Messages appear here. Send a prompt to start.',
        placement: 'left',
        type: 'info',
      },
    ],
  },
  multiChatNav: {
    id: 'multiChatNav',
    title: 'Multi-Agent (MA)',
    description: 'Swarm chat',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/multi-chat',
    steps: [
      {
        target: '.multi-agent-chat',
        content: 'Select multiple agents to respond together.',
        placement: 'center',
        action: 'highlight',
      },
    ],
  },
  autonomousNav: {
    id: 'autonomousNav',
    title: 'Autonomous (AT)',
    description: 'Task runner',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/autonomous',
    steps: [
      {
        target: '.page-heading',
        content: 'Describe a task and let the system orchestrate agents.',
        placement: 'bottom',
        type: 'info',
      },
    ],
  },
  fusionLabNav: {
    id: 'fusionLabNav',
    title: 'Fusion Lab (FL)',
    description: 'Blend agents',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/fusion-lab',
    steps: [
      {
        target: '.page-heading',
        content: 'Blend two or more agents into a new hybrid.',
        placement: 'bottom',
        type: 'info',
      },
    ],
  },
  evolutionLabNav: {
    id: 'evolutionLabNav',
    title: 'Evolution Lab (EL)',
    description: 'Refine iteratively',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/evolution-lab',
    steps: [
      {
        target: '.page-heading',
        content: 'Iterate and improve agents over multiple generations.',
        placement: 'bottom',
        type: 'info',
      },
    ],
  },
  analyticsNav: {
    id: 'analyticsNav',
    title: 'Analytics (AN)',
    description: 'Performance insights',
    duration: '3 min',
    difficulty: 'beginner',
    route: '/analytics',
    steps: [
      {
        target: '.page-heading',
        content: 'Analytics shows performance trends for your agents.',
        placement: 'bottom',
        type: 'info',
      },
    ],
  },
  profileNav: {
    id: 'profileNav',
    title: 'Profile & Security',
    description: 'Account settings and security',
    duration: '2 min',
    difficulty: 'beginner',
    route: '/profile',
    steps: [
      {
        target: '.page-heading',
        content: 'Manage your profile, security, and account settings here.',
        placement: 'bottom',
        type: 'info',
      },
    ],
  },

  multiAgentChat: {
    id: 'multiAgentChat',
    title: 'Multi-Agent Chat',
    description: 'Learn how to have conversations with multiple agents',
    duration: '8 min',
    route: '/multi-chat',
    difficulty: 'intermediate',
    steps: [
      {
        target: '.multi-agent-chat',
        content: 'Welcome to Multi-Agent Chat! Here you can have multiple agents discuss topics and provide different perspectives.',
        placement: 'center',
        action: 'highlight',
      },
      {
        target: '.agent-selector',
        content: 'This is the agent selection panel. Choose which agents you want to participate in the conversation.',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.agent-list-selector',
        content: 'Check the boxes to select your agents. You can select as many as you want!',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.message-input input',
        content: 'Type your topic or question here and all selected agents will respond.',
        placement: 'top',
        action: 'input',
      },
      {
        target: '.chat-messages-area',
        content: 'Watch as your agents respond with their unique perspectives. Each agent brings different insights!',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: 'body',
        content: 'Multi-agent conversations are great for brainstorming, research, and exploring diverse viewpoints!',
        placement: 'center',
        action: 'complete',
      },
    ],
  },

  agentBuilder: {
    id: 'agentBuilder',
    title: 'Advanced Agent Builder',
    description: 'Create powerful AI agents with detailed configurations',
    duration: '12 min',
    route: '/builder',
    difficulty: 'intermediate',
    steps: [
      {
        target: 'header',
        content: 'Welcome to the Agent Builder! Here you can create and configure AI agents with precise control.',
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: '#agentName',
        content: 'Start by giving your agent a clear, descriptive name. This helps you identify it later.',
        placement: 'bottom',
        action: 'input',
      },
      {
        target: '#agentDesc',
        content: "Describe what your agent does and who it's for. This context helps the agent stay focused.",
        placement: 'bottom',
        action: 'textarea',
      },
      {
        target: '#agentPrompt',
        content: 'Write detailed system instructions here. This is where you define your agent\'s behavior, tone, and expertise.',
        placement: 'left',
        action: 'textarea',
      },
      {
        target: '.config-column section:nth-child(2)',
        content: 'Use Personality sliders to fine-tune your agent. Formality controls professionalism, Creativity controls imaginativeness.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '.toggle',
        content: 'Guardrails help control your agent\'s behavior. Enable them to ensure factuality and prevent opinions.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '.chat-column',
        content: 'Test your agent here! Type messages and see how it responds in real-time.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '.header-actions button:contains("publish")',
        content: 'When you\'re happy with your agent, publish it to make it available for chats and workflows.',
        placement: 'bottom',
        action: 'button',
      },
      {
        target: 'body',
        content: 'Congratulations! You\'ve mastered the Agent Builder. Now create amazing AI agents!',
        placement: 'center',
        action: 'complete',
      },
    ],
  },

  chatSurface: {
    id: 'chatSurface',
    title: 'Chat Surface',
    description: 'Learn how to interact with agents in the chat interface',
    duration: '5 min',
    difficulty: 'beginner',
    route: '/chat',
    steps: [
      {
        target: 'header',
        content: 'The Chat Surface is where you test and interact with individual agents before deployment.',
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: '.chat-rail',
        content: 'This sidebar shows all your published agents. Click one to start chatting with it.',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.rail-item',
        content: 'Each agent is displayed with its avatar and name. Select the agent you want to chat with.',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.stage-header',
        content: "Here you can see the selected agent's name and description. This helps you understand the agent's purpose.",
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: '.stage-window',
        content: "The chat history appears here. You'll see your messages and the agent's responses.",
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '.stage-input input',
        content: 'Type your message here and press Enter or click Send to chat with the agent.',
        placement: 'top',
        action: 'input',
      },
      {
        target: '.chat-sidebar',
        content: 'The capabilities panel shows the agent\'s configuration like model, formality, and creativity settings.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: 'body',
        content: 'Perfect! You now know how to use the Chat Surface to test your agents!',
        placement: 'center',
        action: 'complete',
      },
    ],
  },

  workflowCanvas: {
    id: 'workflowCanvas',
    title: 'Workflow Canvas',
    description: 'Create complex workflows by connecting AI agents and actions',
    duration: '15 min',
    difficulty: 'advanced',
    route: '/canvas',
    steps: [
      {
        target: '#flowCanvasHeader',
        content: 'Welcome to the Workflow Canvas! Generate workflows from prompts and refine them visually.',
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: '#flowCanvasPrompt',
        content: 'Start by describing the workflow you want. Press Generate to create nodes.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '#flowCanvasNodes',
        content: 'Generated nodes appear here. Click a node for details or drag to reorder.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '#flowCanvasSidebar',
        content: 'The sidebar shows prompt summary, stats, and actions like explain, simulate, and save.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '#flowCanvasCreateAgent',
        content: 'When you like the workflow, create an agent from it here.',
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: 'body',
        content: 'You now master Workflow Canvas! Create powerful automated workflows by combining triggers, agents, and actions.',
        placement: 'center',
        action: 'complete',
      },
    ],
  },

  voiceChat: {
    id: 'voiceChat',
    title: 'Voice Chat with Agents',
    description: 'Have real-time conversations with AI agents using your voice',
    duration: '4 min',
    difficulty: 'intermediate',
    route: '/voice-chat',
    steps: [
      {
        target: '.brand',
        content: 'Welcome to Voice Chat! Have real-time conversations with your AI agents using speech recognition.',
        placement: 'bottom',
        action: 'highlight',
      },
      {
        target: '.agent-selector',
        content: 'First, select an agent from this list. Your published agents will appear here.',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.agent-option',
        content: 'Click on any agent to select it. The agent will be highlighted when active.',
        placement: 'right',
        action: 'highlight',
      },
      {
        target: '.voice-stage',
        content: 'This is the main chat area. Agent responses will appear here, and you can see your conversation history.',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: '.status-badge',
        content: 'Check this status badge to see if you are listening, speaking, or ready to chat.',
        placement: 'top',
        action: 'highlight',
      },
      {
        target: '.control-btn',
        content: 'Click "Start Listening" to begin recording. Your speech will be converted to text automatically.',
        placement: 'top',
        action: 'highlight',
      },
      {
        target: '.transcript-box',
        content: 'Your transcribed speech will appear here. You can verify it before sending.',
        placement: 'top',
        action: 'highlight',
      },
      {
        target: '.info-panel',
        content: 'Check out the tips panel for best practices. Speak clearly and in quiet environments for best results!',
        placement: 'left',
        action: 'highlight',
      },
      {
        target: 'body',
        content: 'Perfect! You now know how to use Voice Chat. Start a conversation with your AI agents!',
        placement: 'center',
        action: 'complete',
      },
    ],
  },
};

export const getTutorial = (tutorialId) => {
  return tutorialSteps[tutorialId];
};

export const getAllTutorials = () => {
  return Object.values(tutorialSteps);
};
