/**
 * Tool System Test Examples
 * 
 * Run these tests to verify the tool system is working correctly
 * 
 * Usage:
 *   node test-tools.js
 */

import fetch from 'node-fetch';

const BASE_URL = 'http://localhost:4000';

/**
 * Utility function to make API calls
 */
async function apiCall(endpoint, method = 'GET', body = null) {
  const options = {
    method,
    headers: { 'Content-Type': 'application/json' },
  };

  if (body) {
    options.body = JSON.stringify(body);
  }

  const response = await fetch(`${BASE_URL}${endpoint}`, options);
  const data = await response.json();

  if (!response.ok) {
    throw new Error(`API Error: ${response.status} - ${JSON.stringify(data)}`);
  }

  return data;
}

/**
 * Test 1: Get available tools
 */
async function testGetTools() {
  console.log('\n=== Test 1: Get Available Tools ===');
  try {
    const result = await apiCall('/api/tools');
    console.log(`✓ Found ${result.count} tools:`);
    result.tools.forEach(tool => {
      console.log(`  - ${tool.name} (${tool.id}): ${tool.description}`);
    });
    return true;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 2: Write a file
 */
async function testWriteFile() {
  console.log('\n=== Test 2: Write File ===');
  try {
    const result = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'writeFile',
      params: {
        filename: 'test-report.txt',
        content: 'This is a test report created by the tool system.\n\nIt contains sample data and demonstrates file writing capabilities.',
        format: 'text',
      },
    });

    if (result.success) {
      console.log('✓ File written successfully');
      console.log(`  Filename: ${result.result.filename}`);
      console.log(`  Size: ${result.result.size} bytes`);
    } else {
      console.error('✗ Tool execution failed:', result.error);
    }
    return result.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 3: List files
 */
async function testListFiles() {
  console.log('\n=== Test 3: List Files ===');
  try {
    const result = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'listFiles',
      params: {},
    });

    if (result.success) {
      console.log(`✓ Found ${result.result.count} files in outputs directory:`);
      result.result.files.forEach(file => {
        console.log(`  - ${file.name} (${file.size} bytes)`);
      });
    } else {
      console.error('✗ Tool execution failed:', result.error);
    }
    return result.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 4: Read a file
 */
async function testReadFile() {
  console.log('\n=== Test 4: Read File ===');
  try {
    const result = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'readFile',
      params: {
        filename: 'test-report.txt',
      },
    });

    if (result.success) {
      console.log('✓ File read successfully');
      console.log(`  Content (first 100 chars): ${result.result.content.substring(0, 100)}...`);
    } else {
      console.error('✗ Tool execution failed:', result.error);
    }
    return result.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 5: Generate a report
 */
async function testGenerateReport() {
  console.log('\n=== Test 5: Generate Report ===');
  try {
    const result = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'generateReport',
      params: {
        title: 'Sample Report',
        sections: [
          {
            title: 'Introduction',
            content: 'This is a sample report generated by the tool system.',
          },
          {
            title: 'Key Findings',
            content: 'The tool system is working correctly and can:\n- Read files\n- Write files\n- Generate reports\n- Analyze data\n- Execute code',
          },
          {
            title: 'Conclusion',
            content: 'The agent tool system is fully functional and ready for use.',
          },
        ],
        format: 'html',
      },
    });

    if (result.success) {
      console.log('✓ Report generated successfully');
      console.log(`  Filename: ${result.result.filename}`);
      console.log(`  Format: ${result.result.format}`);
    } else {
      console.error('✗ Tool execution failed:', result.error);
    }
    return result.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 6: Execute code
 */
async function testExecuteCode() {
  console.log('\n=== Test 6: Execute Code ===');
  try {
    const result = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'executeCode',
      params: {
        code: 'return { message: "Code execution works!", timestamp: new Date().toISOString() };',
      },
    });

    if (result.success) {
      console.log('✓ Code executed successfully');
      console.log(`  Result: ${result.result.result}`);
    } else {
      console.error('✗ Tool execution failed:', result.error);
    }
    return result.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 7: Parse and execute tool calls from agent response
 */
async function testProcessResponse() {
  console.log('\n=== Test 7: Process Agent Response with Tool Calls ===');
  try {
    const agentResponse = `
      I've analyzed your requirements and will now create a summary document.
      
      [TOOL_CALL: listFiles({})]
      
      Now I'll create a summary:
      
      [TOOL_CALL: writeFile({"filename": "summary.txt", "content": "This is an automatically generated summary."})]
      
      The summary has been created successfully. You can find it in the outputs folder.
    `;

    const result = await apiCall('/api/tools/process-response', 'POST', {
      responseText: agentResponse,
    });

    console.log('✓ Response processed successfully');
    console.log(`  Tool calls found: ${result.toolCalls.length}`);
    result.toolCalls.forEach((tc, i) => {
      console.log(`    ${i + 1}. ${tc.tool}`);
    });
    console.log(`  Tool results: ${result.results.length}`);
    result.results.forEach((tr, i) => {
      console.log(
        `    ${i + 1}. ${tr.tool}: ${tr.success ? '✓ Success' : '✗ Failed'}`
      );
    });

    return true;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Test 8: Create sample data and analyze it
 */
async function testDataAnalysis() {
  console.log('\n=== Test 8: Create and Analyze Data ===');
  try {
    // Create a CSV file
    const csvContent = `name,sales,region
      Product A,15000,North
      Product B,22000,South
      Product C,18500,East
      Product D,25000,West
      Product E,19500,North`;

    const writeResult = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'writeFile',
      params: {
        filename: 'sample-sales.csv',
        content: csvContent,
        format: 'text',
      },
    });

    if (!writeResult.success) {
      throw new Error('Failed to create sample CSV');
    }

    console.log('✓ Sample CSV created');

    // Analyze the data
    const analyzeResult = await apiCall('/api/tools/execute', 'POST', {
      toolId: 'analyzeData',
      params: {
        filename: 'sample-sales.csv',
        operation: 'statistics',
        column: 'sales',
      },
    });

    if (analyzeResult.success) {
      console.log('✓ Data analyzed successfully');
      const stats = analyzeResult.result;
      console.log(`  Count: ${stats.count}`);
      console.log(`  Mean: ${stats.mean}`);
      console.log(`  Min: ${stats.min}`);
      console.log(`  Max: ${stats.max}`);
      console.log(`  Range: ${stats.range}`);
    } else {
      console.error('✗ Analysis failed:', analyzeResult.error);
    }

    return analyzeResult.success;
  } catch (error) {
    console.error('✗ Failed:', error.message);
    return false;
  }
}

/**
 * Run all tests
 */
async function runAllTests() {
  console.log('╔════════════════════════════════════════════╗');
  console.log('║   Agent Tool System - Test Suite           ║');
  console.log('╚════════════════════════════════════════════╝');

  const tests = [
    testGetTools,
    testWriteFile,
    testListFiles,
    testReadFile,
    testGenerateReport,
    testExecuteCode,
    testProcessResponse,
    testDataAnalysis,
  ];

  let passed = 0;
  let failed = 0;

  for (const test of tests) {
    try {
      const result = await test();
      if (result) {
        passed++;
      } else {
        failed++;
      }
    } catch (error) {
      console.error('Unexpected error:', error.message);
      failed++;
    }
  }

  console.log('\n╔════════════════════════════════════════════╗');
  console.log(`║   Tests Passed: ${passed}/${tests.length}`.padEnd(43) + ' ║');
  console.log(`║   Tests Failed: ${failed}/${tests.length}`.padEnd(43) + ' ║');
  console.log('╚════════════════════════════════════════════╝\n');

  process.exit(failed > 0 ? 1 : 0);
}

// Run tests if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllTests().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { apiCall, testGetTools, testWriteFile, testListFiles, testReadFile, testGenerateReport, testExecuteCode, testProcessResponse, testDataAnalysis };
